[project]
name = "qa-pytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "isort>=6.0.1",
    "mypy>=1.16.0",
    "pre-commit>=4.2.0",
    "pytest==8.2.2",
    "ruff>=0.11.13",
]

# Linters
[tool.ruff]
extend = "ruff.toml"

unfixable = []


[tool.mypy]
python_version = "3.9"

follow_imports = "silent"
disable_error_code = "import-untyped"
ignore_missing_imports = true


[tool.pytest]
minversion = "8.2.2"

[tool.pytest.ini_options]
addopts = ["--strict-markers", "-s", "-v"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "smoke: basic smoke tests to verify critical functionality",
    "positive: tests with correct result",
]
